run 'ex_pose_goal' example

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -50,3 +50,17 @@ jobs:
         if: ${{ matrix.deb == env.CODENAME }}
         run: |
           sudo apt -y install ros-${{ matrix.ros }}-ros2cli-common-extensions
+
+      - name: Run 'ex_pose_goal' example
+        if: ${{ matrix.deb == env.CODENAME }}
+        run: |
+          . /opt/ros/${{ matrix.ros }}/setup.bash
+          # do not exit on first failure to allow processing the timeout exit code
+          set +e
+          timeout --preserve-status 5s ros2 run pymoveit2 ex_pose_goal.py
+          status=$?
+          set -e
+          echo "timeout status: " $status
+          # success on timeout or command success
+          # 143 = 128 + SIGTERM
+          [ $status -eq 0 ] || [ $status -eq 143 ] || exit $status
